### ISSUE TITLE
'Open Data' Icon Missing From Recently Added Datasets

### ISSUE THREAD

**Issue by wendyrogers** [ViderumGlobal/ckanext-iati#105]
When viewing a the list of datasets on the publisher account eg https://iatiregistry.org/publisher/jica the new files also do not have the 'Open Data' icon set?

**Comment by dalepotter** [comment]
@chrisviderum Not sure if any work was done on this one, but clicking the link supplied by @wendyrogers no longer shows this issue - perhaps it was related to the publisher's choice of data license...?

Wendy, do flag if this issue reappears.

**Comment by wendyrogers** [comment]
Yes thanks @dalepotter all looks okay now

**Comment by chrisviderum** [comment]
@dalepotter as far as I know we haven't done any work on this ticket, but the icons are there.

@wendyrogers do you know, if Dale suggestions could be correct?

**Comment by wendyrogers** [comment]
@chrisviderum This issue appears to have been resolved now. I had assumed that it was related to the issue of the metadata not being updated which has also now been resolved.

Therefore I am happy to close this issue now.
