### ISSUE TITLE
Unknown SSL protocol error 443

### ISSUE THREAD

**Issue by sachit-singh** [ViderumGlobal/ckanext-iati#118]
Unknown SSL protocol Error 443 is thrown by the registry api. However, it has not been deterministic. We get the correct response sometimes but is very very slow. And sometimes the unknown protocol error 443 is thrown.

**Comment by pmartignoli** [comment]
@sachit-singh. Can you please tell me which api call (calls?) you are making to produce this error?

**Comment by sachit-singh** [comment]
@pmartignoli during the time of issue, the responses were very slow and at times they gave unknown ssl protocol error and the publishing took too long and failed at times. But I doubt if its a problem with the api. Its alright now.
