### ISSUE TITLE
IATIRegistry API throwing an Internal Server Error[500]

### ISSUE THREAD

**Issue by sachit-singh** [ViderumGlobal/ckanext-iati#120]
The registry update api returns Internal Server Error [500]. I don't know if its the same for the create api as well.

**Comment by kmbn** [comment]
What API call are you referring to? `package_update`, `resource_update`, or one of the other update functions? And is the API returning a 500 error in general or only when you try to update a specific dataset, resource, etc.?

**Comment by sachit-singh** [comment]
The `package_update` api was throwing the 500 error...I don't know what the problem was, but it is not now...for a certain time there was a problem with the api and thus I had opened up the issue. Was there any changes due to which the error might have occured. During the time of the error, no matter how may times we tried, there was a 500 error raised. But its fine now. Thank you.
