### ISSUE TITLE
'Filter results' button not working

### ISSUE THREAD

**Issue by dalepotter** [ViderumGlobal/ckanext-iati#121]
On a publisher's list of datasets, clicking the `Filter Results` button does nothing. This seems to affect all publishers. An example is the [DfID publisher page](https://iatiregistry.org/publisher/dfid):

![image](https://cloud.githubusercontent.com/assets/8247168/26724701/bc86e370-4792-11e7-8cf1-ccc3f743e0ea.png)

I have tried this using Chrome version 58.0.3029.110 (64-bit and) Firefox 53.0.3 (64-bit) - both on a Mac.

**Comment by pmartignoli** [comment]
This "Filter Results" button should only be visible on mobile devices or small screens. There was an issue with css classes which has been resolved.

The button functionality however is not working. As this is a CKAN core issue, we have created the following ticket and are awaiting their response. https://github.com/ckan/ckan/issues/3593

**Comment by dalepotter** [comment]
Thanks for the earlier update @pmartignoli just to add a further update the issue following our call this morning... 

As you and @JGulic mentioned, a fix has now been added in line with the reported issue: ckan/ckan#3593 which is available in CKAN version 2.6.2. This version can be deployed to the staging environment, where manual checks can be done to test other functionality. This is with a view to deploying 2.6.2 to the production site in due course.

**Comment by pmartignoli** [comment]
@dalepotter I have opened a new issue for the 2.6.2 upgrade and propose we close this solved issue
