### ISSUE TITLE
Upgrade IATI Registry to CKAN 2.6.2

### ISSUE THREAD

**Issue by pmartignoli** [ViderumGlobal/ckanext-iati#126]
@dalepotter 
As discussed last Friday, updating the registry to 2.6.2 will be beneficial for a number of reasons and should be carried out prior to any further developments.

Below is the current plan. 

1.	Upgrade staging to 2.6.2. 
2.	Ensure all extensions are operating as expected. 
3.	Make any required changes
4.	Add initial tests to Archiver
5.	Write initial tests for IatiPublishers
6.	Write initial tests for IatiDatasets
7.	Test IatiCSVImport (test exists but we need to make sure that since the test was written there aren't any changes applied to this plugin)

We would like to proceed this week with points 1 and 2 which are estimated to require 10 hours development time. Please let me know if you are happy to go ahead with points 1 and 2.

**Comment by dalepotter** [comment]
Thanks @pmartignoli and apologies for the delay. Yes happy to proceed with points 1 and 2.

**Comment by pmartignoli** [comment]
@dalepotter IATI has been upgraded to 2.6.2

**Comment by dalepotter** [comment]
As both the [staging](https://iati-staging.ckan.io/api/3/action/status_show) and [production](https://iatiregistry.org/api/3/action/status_show) instances have been upgraded to CKAN 2.6.2, this issue can now be closed.

![image](https://user-images.githubusercontent.com/8247168/28966548-b1ce38f4-790e-11e7-88b8-de9b6ef0c153.png)

**Comment by andylolz** [comment]
I don’t know if it’s useful to do something [similar to this](http://www.aidtransparency.net/news/important-changes-to-the-iati-registry-api) to let registry API users know about this change? (albeit retrospectively.)

Just checking [the changelog](http://docs.ckan.org/en/latest/changelog.html), I notice 2.6.2 isn’t listed… Looks like there’s never a changelog provided for old point versions.

**Comment by newkdukem** [comment]
@andylolz I believe that the changelog for [2.6.2](http://docs.ckan.org/en/ckan-2.6.3/changelog.html#v2-6-2-2017-03-22) is placed under the 2.6.3 one. By my understanding, the changelogs are categorized in major releases (eg. 2.6 or 2.7).

**Comment by andylolz** [comment]
Aha! That’s useful to know. Thanks, @newkdukem.
