### ISSUE TITLE
IATI Registry user accounts- new button for regenerating API key

### ISSUE THREAD

**Issue by PetyaKangalova** [ViderumGlobal/ckanext-iati#132]
I have just noticed that there is a new feature in the IATI Registry user account section allowing admins to re-set password (which is indeed useful). There is also a new button allowing regeneration of API Key. 

This is not an issue in itself and a low priority in the list, but mainly a question to understand when the new feature was added (see screenshot below).

Many thanks,
Petya

![image](https://user-images.githubusercontent.com/24607542/29075935-e184221c-7c4b-11e7-819e-14b9f129450f.png)

**Comment by newkdukem** [comment]
@PetyaKangalova As far as I know this is a regular CKAN behaviour. I have checked the change-log for CKAN v2.6.x and didn't find differences on that part of CKAN. 
What I've found helpful is that this feature is in the [documentation](http://docs.ckan.org/en/ckan-2.2.3/sysadmin-guide.html#managing-users) for CKAN v2.2.3

**Comment by newkdukem** [comment]
@PetyaKangalova If there are no additional information required, regarding the "Regenerate API Key" button, is it OK to close this issue?

**Comment by PetyaKangalova** [comment]
@newkdukem Many thanks for the update and letting me know that this is part of regular CKAN behaviour. I will close the issue now.
