### ISSUE TITLE
Validator fails for the (valid) dataset name `ec-devco-ec`

### ISSUE THREAD

**Issue by andylolz** [ViderumGlobal/ckanext-iati#149]
This dataset name is considered invalid:
https://iatiregistry.org/dataset/ec-devco-ec

That’s due to the second clause in this conditional:
https://github.com/ViderumGlobal/ckanext-iati/blob/caec677ee668b026b972be73f7edadb8fbe8f985/ckanext/iati/logic/validators.py#L81

It’s failing here because the first part of the org name ‘ec’ (the European Commisson) matches the code ‘ec’ (Ecuador). However, this is a failure on the part of the validator – there’s no reason to block such a dataset name.

I think the clause is trying to say: the value must be made up of an org name and a (non-empty) code, separated by a hyphen. If so, using sets to do this is not correct, since it adds the arbitrary restriction that the code can’t equal the org name, or any ‘segment’ of it.

**Comment by dalepotter** [comment]
@minnaholi Please could you take a look at this issue (along with the suggested fix that @andylolz has kindly provided in PR #150) and action/comment as appropriate.

**Comment by goranmaxim** [comment]
The regex solution kindly provided by @andylolz was tested and deployed on staging and has successfully ran without any issues. Since this is a bug fix, as previously noted, it was also directly deployed on production as well.
