### ISSUE TITLE
SSL cert won’t verify without SNI support

### ISSUE THREAD

**Issue by andylolz** [ViderumGlobal/ckanext-iati#158]
https://www.ssllabs.com/ssltest/analyze.html?d=iatiregistry.org

**Comment by mbocevski** [comment]
Yes that’s correct, one must use SNI. Is that an issue? Do you have a very legacy library or browser that someone is using?

**Comment by andylolz** [comment]
> Do you have a very legacy library or browser

Not a browser, no – my issue is specifically with using the API programmatically, via the [ckanapi](https://pypi.python.org/pypi/ckanapi) library.

There’s no way to tell ckanapi not to verify certificates, and I’m trying to use it with python2 on a system without pyOpenSSL. That setup doesn’t work without no-SNI support.

Downgrading to [ckanclient](https://github.com/okfn/ckanclient-deprecated) solves the issue.

**Comment by mbocevski** [comment]
Any reason you can’t install pyOpenSSL? You can also contribute to ckanapi an option not to verify certificates.

Considering SNI has been around for more than 10 years and is supported by virtually every browser and libraries out there I don’t think that I would consider this an issue unless you have very specific use cases (typically very legacy systems/software) that require that. If the latter is the case we can see about getting a separate IP address to do SSL termination superficially for the domain, which is a change.

**Comment by andylolz** [comment]
> You can also contribute to ckanapi an option not to verify certificates.

I considered this, but i strongly suspect such a PR wouldn't be accepted. I'm not averse to contributing to other people's open source projects, as you'll know from my PRs to this repo! E.g. #153; #154
