### ISSUE TITLE
“Error 503 Backend fetch failed” on all pages

### ISSUE THREAD

**Issue by andylolz** [ViderumGlobal/ckanext-iati#159]
![screen shot 2018-01-10 at 10 24 15](https://user-images.githubusercontent.com/464193/34767601-722e4784-f5f0-11e7-86ce-2238ce6457b4.png)

**Comment by minnaholi** [comment]
Hi @andylolz, we are aware of this, and our engineers are working on resolving the issue with the highest priority.

**Comment by andylolz** [comment]
Same issue is occurring again today.

**Comment by andylolz** [comment]
Day 3:

![screen shot 2018-01-12 at 12 06 58](https://user-images.githubusercontent.com/464193/34874518-232e1f40-f791-11e7-81e5-3ad277d68675.png)

**Comment by minnaholi** [comment]
@andylolz  Our engineers are working on restoring the service as soon as possible.

**Comment by andylolz** [comment]
![screen shot 2018-01-16 at 15 50 08](https://user-images.githubusercontent.com/464193/34997707-fd5f00ee-fad4-11e7-9321-523fd9c23d9f.png)

**Comment by andylolz** [comment]
Looks like there were 9 hours of downtime overnight:

![screen shot 2018-01-18 at 11 54 44](https://user-images.githubusercontent.com/464193/35097180-0006fdc4-fc47-11e7-9f4b-7a9e58bd3da3.png)

Apparently that’s a year’s worth of downtime for a 99.9% uptime SLA: https://uptime.is/99.9

**Comment by andylolz** [comment]
This seems to be doing much better lately:
https://istheiatiregistrydown.treadsoft.ly

Going to close this issue.
