### ISSUE TITLE
Make Changes To Publisher IATI Identifier Field

### ISSUE THREAD

**Issue by wendyrogers** [ViderumGlobal/ckanext-iati#72]
On the form for the 'Admin' section of a publisher account eg http://iatiregistry.org/publisher/edit/dipr the label for the field 'IATI Identifier' should be changed to 'IATI Organisation Identifier'. This field should also be mandatory.

In addition, the help information underneath this field should be amended from:

'The organisation identifier used in the IATI-xml files to identify the reporting organisation. (<reporting-org ref="!!!">).'

to

'The organisation identifier used in the IATI XML files to identify the reporting organisation. For more information please go to http://iatistandard.org/202/organisation-identifiers'

**Comment by peppe1337** [comment]
@dalepotter this should be already implemented on the v.2.5.2 staging site.

**Comment by chrisviderum** [comment]
@wendyrogers  this fix is now live.

**Comment by wendyrogers** [comment]
@chrisviderum thank you and all looks fine so happy to close issue

**Comment by dalepotter** [comment]
A fix for this issue has been deployed to the live instance of the IATI Registry. Therefore this issue is being closed.
