### ISSUE TITLE
Restore the link to the CSV export functionality

### ISSUE THREAD

**Issue by dalepotter** [ViderumGlobal/ckanext-iati#73]
We would like to reinstate the link to download an activity file in CSV format. This used to exist on the activity page, but was removed over the summer (2015).

The link pointed to `http:/tools.aidinfolabs.org/csv/direct_from_registry/?xml=[URL of activity file]` - for example: `http:/tools.aidinfolabs.org/csv/direct_from_registry/?xml=http%3A//iati.dfid.gov.uk/iati_files/Country/DFID-Afghanistan-AF.xml`

This [screenshot from the Internet Archive's 'Wayback machine'](https://web.archive.org/web/20150324001159/http://iatiregistry.org/publisher/dfid) shows how the link used to appear:

![image](https://cloud.githubusercontent.com/assets/8247168/13223885/0af4ba16-d97e-11e5-81db-25bd01e0ce15.png)

Possibly relevant commit: https://github.com/okfn/ckanext-iati/commit/33fe3962d00613cb18a39657c501464aa42febb7

**Comment by dalepotter** [comment]
This issue appears to be have bene addressed in 40f4bbb. 

Once deployed to the live instance, this issue can be closed

**Comment by chrisviderum** [comment]
@dalepotter this should be live now. Correct?

**Comment by dalepotter** [comment]
A fix for this issue has been deployed to the live instance of the IATI Registry. Therefore this issue is being closed.
