### ISSUE TITLE
Add 'Date First Published' To Publisher Accounts

### ISSUE THREAD

**Issue by wendyrogers** [ViderumGlobal/ckanext-iati#76]
From a registry management perspective it is extremely useful for us to know when (date) an organisation publishes IATI XML files to the IATI Registry for the very first time. Therefore, we should add this field to all publisher accounts. The field should be a read only field (so it can not be changed via the user interface) and only updated once. 

When this field is added we would also want to populate this information for publishers who are already publishing perhaps by uploading information from a spreadsheet and matching data on 'Publisher ID'?

**Comment by dalepotter** [comment]
@chrisviderum would you be able to provide a time estimate to add this feature?

**Comment by chrisviderum** [comment]
@dalepotter @wendyrogers 

You will receive an estimation on Friday. Tomorrow is a national holiday for most of our development staff, so I hope it is okay that you may receive it a bit after 9am London time.

**Comment by peppe1337** [comment]
@dalepotter @wendyrogers 

Just to doublecheck:  This field should have a date as soon as a user uploaded a file through:  https://iati-staging.ckan.io/csv/upload the first time?

Thanks for your help!

**Comment by chrisviderum** [comment]
Wrong account. I will learn it one day. Sorry!

**Comment by chrisviderum** [comment]
The estimation here would be 2days of development work and 0.5-1 day of testing.

**Comment by wendyrogers** [comment]
Many thanks @chrisviderum and I wanted to confirm that the 'date first published' field should normally only be updated on the very first time that any file is first added to a publisher account via the populating of the URL field of a dataset. However, the populating of the URL field can also be done manually via the Registry online interface or via the API and so is not just through the upload function:  https://iati-staging.ckan.io/csv/upload 

Also, the 'date first published' field should only ever be available to 'Admin' users (NB not the publisher owner) to update through the Registry interface and the requirement for 'Admin' users to update via spreadsheet is just so that once the field has been added we can do a one off backload of information for all publishers who are already publishing

I therefore hope that helps and please let us know if you need more information or if that changes the estimates? TIA

**Comment by chrisviderum** [comment]
Thank you very much for this update.

I will get back to you with a new estimation, soon.

**Comment by chrisviderum** [comment]
@wendyrogers what is meant with "via the populating of the URL field"? 

This is the only thing we are not 100% sure about. Can we make it a general rule for the first time a publisher has uploaded in general a dataset?

If not, can you please describe, how a user can upload a dataset that it will be counted? I understood that one way is through an upload via https://iati-staging.ckan.io/csv/upload, but what are the other options?

Thanks for your help.

**Comment by wendyrogers** [comment]
@chrisviderum When a publisher creates a dataset we need them to provide a valid URL in the 'URL' field of the 'Data file' section when creating a dataset.  That URL ideally needs to reference an IATI XML file (and not an html or other file type).  It is only when a valid URL has been provided that we consider a publisher to have 'published'. I think that it is also currently possible to create a dataset without specifying a value for the URL?

It is also my understanding that a dataset can be created by any of the following ways:
- manually via the web user interface
- via the Registry API
- via the CSV upload function

If it is easier to talk this through so that I can demonstrate the above please email the IATI Help Desk at support@iatistandard.org so we can schedule a call.

**Comment by chrisviderum** [comment]
@wendyrogers thanks you very much. I will get back very soon!

**Comment by chrisviderum** [comment]
The estimations are still the same.

2 days of development at all and 0.5 - 1 day of testing.

**Comment by chrisviderum** [comment]
@wendyrogers thanks for your help with giving the information.

Would you like to have this added to the new portal?

**Comment by dalepotter** [comment]
Thanks for this estimation @chrisviderum We would like to add this feature, however we would like to wait until our version of CKAN has been [upgraded to v2.5.2](http://www.aidtransparency.net/news/important-changes-to-the-iati-registry-api) (week beginning 10th October).

I will give the formal go-ahead at some point after this.

**Comment by chrisviderum** [comment]
@dalepotter @wendyrogers 

Just to let you know:  We are working on this feature now.

During our first investigations we ran into some problems, about which I would like to inform you and where I need your decision on:


1. Already existing publishers

We only have information regarding the data which is currently uploaded. So we would take the creation_date of the first uploaded data of the current publishers. There could be the possiblity that publishers have published a dataset already earlier, but deleted it. 

2. Missing "created" key

Some of the datasets in the database are missing the key "created" which is the creation_date.
They were added a long time ago (2012) and CKAN didn't support that key at this time. So we can't find this out for these dataset.

 But, there is a "last_modified" key, which is the date the resource was last modified.
Should we consider this field instead as a fallback if the creation_date is not available?


Thank you for your help!

**Comment by wendyrogers** [comment]
@chrisviderum  we currently maintain the 'first published date' for all existing publishers as part of our CRM. Therefore (as per the first post of this issue) we would like to update this new field on the IATI registry with the CRM information that we currently hold for each existing publisher. I can provide this information (publisher ID & data first published) in Excel format if that would provide a suitable source for updating the IATI Registry from?

However, once implemented then the first published field should be automatically be updated from the creation date of the first published dataset.

**Comment by klikstermkd** [comment]
@wendyrogers Should the date be in the format "YYYY-MM-DD" (e.g. 2016-10-17) ?

**Comment by wendyrogers** [comment]
I think the field should be stored in the same format as for all other dates. However, it should also be displayed in the publisher box in the right hand sidebar under 'HQ Country' and above 'Followers' as:

Date First Published
17 Oct 2017

eg on publisher page https://iatiregistry.org/publisher/asi

**Comment by klikstermkd** [comment]
The feature is now implemented on staging https://iati-staging.ckan.io

If it looks good to you I will push it on production as well.

**Comment by wendyrogers** [comment]
Thakn @klikstermkd I have tried to have a look but every time I try and access a publisher record I am getting a 500 error message Server Error - An internal server error occurred?

Also do you want me to provide a file containing publisher IDs and the dates of first publication for all existing publishers so they can be added as a one off exercise?

**Comment by chrisviderum** [comment]
@wendyrogers sorry for the delay. You shouldn't receive the error message anymore.

https://iati-staging.ckan.io/ 

Hopefully you can give it a try now!

**Comment by wendyrogers** [comment]
Thank you @chrisviderum and having now looked at the changes please could you just the display so that
1) the date is on a separate line to the heading
2) the date is in the format 10 October 2016 

Also, having registered a new user and trying to add a new publisher I am getting an Internal server error 'An internal server error occurred'?

Finally , I will separately email the list of first published dates that will need to be uploaded for existing publishers

**Comment by chrisviderum** [comment]
@wendyrogers changes are provided on iati-staging.ckan.io

The internal server error should be sorted out, too. 

After we received your sign off, we can agree on a release date for this feature.

**Comment by wendyrogers** [comment]
Thx @chrisviderum but when logged in as Admin to the staging site I am still getting the internal server error? 

Also, from a separate discussion you said that it is not possible to update the first published date field for all existing publishers from the excel file I sent to you. Is manually updating each publisher the only option for this?

**Comment by chrisviderum** [comment]
@klikstermkd has fixed the internal server errors. Very strange! Can you take a look at it again, please?

That is correct. Maybe @klikstermkd can give here again another insight, but as far as I understood ti would be the only option.

Thanks for your help.

**Comment by chrisviderum** [comment]
@wendyrogers so you weren't able to test it?

**Comment by dalepotter** [comment]
Hi both, just a couple comments on this from a developer point of view.

1) Could we change how the field appears to users, and reduce the space in between the label and content - for example looking at https://iati-staging.ckan.io/publisher/across:
![image](https://cloud.githubusercontent.com/assets/8247168/19853247/02834bd8-9f60-11e6-8e28-0e45331b1b5a.png)

Can we change the template to use a new line tag, rather than a paragraph. I.e. from
```
<p>First published date:</p>
<p>02 July 2015</p>
```
to...
```
<p>First published date:<br/>
02 July 2015</p>
```

2) I'm surprised that there is no automated way to batch add our csv spreadsheet of existing dates.  Can we confirm there is no way to do this using the API? Or even my adding a script to amend the backend database that powers our CKAN instance.

**Comment by wendyrogers** [comment]
Thanks for extra comments @dalepotter . Also having carried out some testing I have identified that the publisher account holder can currently update the 'First Published date' field. This should not be the case. Only the IATI Registry administrators (and the automated update from when the first dataset is added) should be able to update this field. It should be read only for the publisher account owner.

**Comment by chrisviderum** [comment]
@dalepotter  we have made this change according to your suggestion. Is this ready to be pushed then?

**Comment by wendyrogers** [comment]
Thanks @chrisviderum . Please can you also confirm if any changes have been made in relation to my comment above with regard to the publisher account holder being able to update this field?

Also, did you get any further with investigating a way to upload the 'first published dates' for existing publishers?

Many thanks

**Comment by pmartignoli** [comment]
Hi @wendyrogers . 

Nice to meet you!  I'm Paul, a new addition to the Viderum support team. 

The "first published date" field can now only be changed by admin and no longer by the publisher.

Regarding uploading the "first published dates" via an Excel file, there is a way to do this for all publishers at once using a script, which we would be very happy to create and execute. 

If you have any further questions please get in touch.

**Comment by PetyaKangalova** [comment]
Hi @pmartignoli  Thanks for the update. 

I have now checked whether the "first published date" fix works. On the admin side, it does work and I was able to update the date for IATI publishers. However, it seems that publishers are also still able to update the date. We tested it with an existing IATI publisher (my colleague at DI) and he was able to update the date, which is what we want to avoid. Could you please look into this again?

Another thing that we spotted, both on publisher and admin side, is that there is an error with the date entry. While the description shows that the entry has been set as 'DD.MM.YYYY', when you enter a date,  it actually comes up as "MM.DD.YYYY". Could that be fixed to ensure that the date is set in the right format?

With regards to uploading the date for all publishers, it is great that it could be done at once using a script. I have now prepared an Excel spreadsheet with all IATI publishers and will send the file to you via Zendesk today.

Thanks again.

**Comment by pmartignoli** [comment]
Hi Petya, Thanks for getting back to me. 

Could you let me know if the "first published date" is being updated through the UI or a different method?

Thank you

**Comment by pmartignoli** [comment]
Hi Petya,

Would you please be able to confirm the date format is being switched?

<img width="372" alt="screen shot 2017-01-12 at 11 19 44 am" src="https://cloud.githubusercontent.com/assets/24956197/21885814/a234eabe-d8b9-11e6-8ef8-c2120a619a3b.png">
<img width="213" alt="screen shot 2017-01-12 at 11 25 40 am" src="https://cloud.githubusercontent.com/assets/24956197/21885901/eb6412be-d8b9-11e6-9d0d-99ca7ff98e6b.png">


I have checked and it appears to be working.

Thanks again.

**Comment by chrisviderum** [comment]
FYI:

I just updated the publisher date for the publisher with id theglobalfund (https://iatiregistry.ckan.io/publisher/theglobalfund) and the correct date is displayed.

Is it correct on your end, too? @PetyaKangalova 

Thanks for your help!

Best,

Chris

**Comment by PetyaKangalova** [comment]
Hi  Paul @pmartignoli ,

On the publisher side, I actually tried again by creating a new account and the first published date is no longer available for publishers to amend, so that has been fixed. Many thanks.

With regards to date format, please see screenshots below. When I enter the date DD.MM.YYYY and then press "Update Publisher", it transfers it to MM.DD.YYYY. When I go back into the account it seems to then put it back to the correct format. If you test it by trying to change it, you will probably see what I mean.
![date published](https://cloud.githubusercontent.com/assets/24607542/21887555/4ab746c0-d8b8-11e6-9918-9571ac833a04.PNG)
![date_published_wrong](https://cloud.githubusercontent.com/assets/24607542/21887605/79a03fa0-d8b8-11e6-9a6c-cdc33c96745e.PNG)

Thanks again.

**Comment by PetyaKangalova** [comment]
@chrisviderum   I just checked and the publisher date for theglobalfund is correct and looks fine. 

Many thanks,
Petya

**Comment by pmartignoli** [comment]
Hi @PetyaKangalova ,
The issue causing the dates to switch should be fixed now. Would you please be able to check and confirm?
Thanks

**Comment by PetyaKangalova** [comment]
Hi @chrisviderum ,
I just checked and it now works with the correct date format.
Many thanks,
Petya

**Comment by pmartignoli** [comment]
Hi @dalepotter @wendyrogers @PetyaKangalova,

The "Date First Published" field has now been added and IATI publishers updated with the Excel file provided. Can we now close this issue?

Thank you very much,
Paul

**Comment by wendyrogers** [comment]
Great! Many thanks Paul. I have done a spot check of a number of publishers and the dates look correct so I will close this issue now
