### ISSUE TITLE
Automate the Regular Running of the IATI Registry Purge 

### ISSUE THREAD

**Issue by wendyrogers** [ViderumGlobal/ckanext-iati#77]
It is my understanding that when a publisher account status is updated to a value of 'Deleted' the record is not actually physically deleted until we have manually run the following command on the IATI Register - http://iatiregistry.org/ckan-admin/trash?__no_cache__=True

This can cause problems for third party Registry users who may want to delete and reuse the URL assigned to a published dataset. Therefore it would be preferable if the purge was automated to run on a more regular basis?

**Comment by chrisviderum** [comment]
@wendyrogers you are correct with your first assumption. After a publisher deleted a dataset it will put into the bin. A Sysadmin can purge the deleted files and frees up the URLs again.

I will ask my team, if we can create a script which runs on a regular basis. What timeframe would work for you? Every day, every week or every month?

**Comment by wendyrogers** [comment]
Thank you @chrisviderum my vote would be for daily but @dalepotter @roryscott what do you think?

Also I think with some of the features available in the later version of the CKAN API this is less of an issue for us now?

**Comment by PetyaKangalova** [comment]
@chrisviderum @pmartignoli  Apologies for the delay in getting back to you on this request.  As  IATI Registry users can delete files at anytime, we would like the purge to run on a daily basis.

Let me know if you need further information and look forward to hearing back with an update on when the purge will be automated.

Many thanks,
Petya

**Comment by dalepotter** [comment]
Just to update on this one, I agree with @PetyaKangalova - a daily purge seems like a good frequency.

**Comment by pmartignoli** [comment]
@dalepotter @PetyaKangalova To set this up and carry out testing would require 6 hours of work.

**Comment by dalepotter** [comment]
Thanks for the update on timings @pmartignoli - let's go ahead with this one.

**Comment by pmartignoli** [comment]
@wendyrogers @PetyaKangalova @dalepotter 
This is tested and deployed to production

**Comment by PetyaKangalova** [comment]
@pmartignoli Thanks for letting us know. I just checked and there are no files in the "Trash" tab but I don't think there is anything else I can check to confirm that this is running properly. Are there any tests set up in place?
 @dalepotter, if you are happy with the way this is set up at the moment, please close the issue.

Thanks again,
Petya

**Comment by dalepotter** [comment]
Thanks @pmartignoli and to your developers for implementing this.  As such I will close this issue.
