### ISSUE TITLE
Generation of dataset metadata appears to be incorrect

### ISSUE THREAD

**Issue by dalepotter** [ViderumGlobal/ckanext-iati#95]
There appears to be a bug in the process to generate metadata to be displayed on the dataset page.

Looking at the a [dataset](https://iatiregistry.org/dataset/ofid-activity1) which appeared to have been uploaded yesterday evening (2016-10-20 20:12), which shows an activity count of 1363.

![image](https://cloud.githubusercontent.com/assets/8247168/19595277/f93be0c6-9780-11e6-99c2-2821af959134.png)

However, inspecting the file shows an activity count of 1369:

```
$ wget https://app1.ofid.org/IATI/OFID_IATI_XML.xml
$ python
>>> from lxml import etree
>>> root = etree.parse('OFID_IATI_XML.xml')
>>> len(root.findall('iati-activity'))
1369
```

This result is also confirmed when opening the file in a text editor and searching  for `<iati-activity`. The same number of occurrences is found.

Is this a bug?

**Comment by wendyrogers** [comment]
Issue updated as another publisher has now reported that they have added new datasets to their publisher account but the dataset metadata has not been updated - https://iatiregistry.org/publisher/jica

**Comment by wendyrogers** [comment]
Another publisher has reported that they have updated their datasets and the metadata does appear to have been updated. However, the IATI Harvester script is now showing in their Activity Tab? https://iatiregistry.org/publisher/activity/ebrd

**Comment by klikstermkd** [comment]
@dalepotter The number of activities is not automatically populated. On the bottom of the register new dataset page, there is a field called ``Num. Activities`` which lets the user enter the number of activities manually.

@wendyrogers Regarding https://iatiregistry.org/publisher/jica which part of the dataset metadata has not been updated?

The ``IATI Harvester Script`` represents the nightly script that checks data linked from the registry. It runs at around midnight (UK time) every day.

**Comment by dalepotter** [comment]
Thanks for clarifying that this is a manual field @klikstermkd  My understanding was also that the `IATI Harvester Script` (or perhaps another process) also updates this user field too - is this correct? 

If so, should the number of activities have automatically updated by now?  I've just tested and 1369 activities are still found in the dataset.

**Comment by wendyrogers** [comment]
@klikstermkd re https://iatiregistry.org/publisher/jica if you look at the most recently added files such as https://iatiregistry.org/dataset/jica-089_2015 you can see that 'IATI data updated' field has not been updated. Also when viewing the the list of datasets on the publisher account eg https://iatiregistry.org/publisher/jica the new files also do not have the 'Open Data' icon set?

**Comment by klikstermkd** [comment]
@wendyrogers  The ``IATI Harvester Script`` behaves like a user, that's why it shows in the Activity tab.

Can you create new issue for missing the "Open Data" icon set?

**Comment by wendyrogers** [comment]
New issue https://github.com/ViderumGlobal/ckanext-iati/issues/105 added for the missing 'Open Data' icons. 

Also why is the IATI Harvester script NOT showing in the Activity Tab for https://iatiregistry.org/publisher/activity/ebrd ? They have recently updated their datasets? Thx @klikstermkd

**Comment by chrisviderum** [comment]
@wendyrogers & @dalepotter :  As far as I understood @klikstermkd this should be fixed on the staging system.

Can you make a test on the staging site today? Then we can see the result tomorrow after the nightly script runs.

**Comment by wendyrogers** [comment]
@chrisviderum  @klikstermkd I have run a test for this on the staging site and this looks to have now been fixed. Please can you now apply to the live site. Many thanks

**Comment by dalepotter** [comment]
@chrisviderum - have this one been deployed out of interest?

I noticed that some other issues have been deployed, so perhaps this one has too?

**Comment by chrisviderum** [comment]
@dalepotter sorry for the late response. This one is deployed, correct.

**Comment by dalepotter** [comment]
As the fix for this has now been deployed, this issue can be closed.
