### ISSUE TITLE
Change header link

### ISSUE THREAD

**Issue by rory09** [ViderumGlobal/ckanext-iati#98]
We will need to change the 'IATI Community' link to from `http://support.iatistandard.org` `http://discuss.iatistandard.org/t/welcome-to-iati-discuss`

![registry-header](https://cloud.githubusercontent.com/assets/7805169/19694982/4d110eb4-9ad9-11e6-8c7b-04dbb8b24b12.png)

This follows a change we have made to the location of our discussion and consultation forums.

@chrisviderum could you provide a time estimate to make this fix?

Many thanks,
Rory Scott
IATI Technical Team

**Comment by chrisviderum** [comment]
We will take care of it.

**Comment by dalepotter** [comment]
Thanks for this @chrisviderum - just to clarify that I created a pull request https://github.com/ViderumGlobal/ckanext-iati/pull/99 which should address this issue. This just needs checking and merging :-)

**Comment by chrisviderum** [comment]
@dalepotter I noticed it this morning. We will review and accept this request.

And FYI: Viderum is owner of this repository now. So let's try to make you an admin here, soon!

**Comment by dalepotter** [comment]
A fix for this issue has now been deployed to the live instance of the [IATI Registry](https://www.iatiregistry.org/). 

Therefore this issue is being closed.
